Model
AM-MLA/WaveNet-Project pull request #1
Opened 2022-11-23 09:07 UTC by Maxime135

1er modèle

2022-11-23 09:09 UTC, Teiwin requested changes
ipynb est vraiment nécessaire?

2022-11-23 09:09 UTC, Teiwin commented on model training.py
> +
alala c'est un test

2022-11-23 09:09 UTC, Maxime135 commented on model training.py
> +
ok c'est bon

2022-11-23 09:10 UTC, Teiwin approved these changes

2022-11-23 09:10 UTC, merged

2022-11-27 10:09 UTC, Maxime135 commented on model training.py
> +).model
Problème sur la dimension entre 2 couches de convolution :
- toute première convolution (avant le bloc de delated causal convolutions)
- première convolution du bloc de delated causal convolutions
(voir dimensions avec le model.h5 sur google drive avec Neutron)